import localFont from "next/font/local";
import "./globals.css";
import HeaderClient from "@/components/global/HeaderClient";
import FooterServer from "@/components/global/FooterServer";

const inter = localFont({
  src: "./fonts/Inter_18pt-Medium.ttf",
  variable: "--font-inter",
});

const nunitoSans = localFont({
  src: "./fonts/NunitoSans_7pt_Condensed-Regular.ttf",
  variable: "--font-nunito-sans",
});

const manrope = localFont({
  src: "./fonts/Manrope-VariableFont_wght.ttf",
  variable: "--font-manrope",
});

const pacifico = localFont({
  src: "./fonts/Pacifico-Regular.ttf",
  variable: "--font-pacifico",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${nunitoSans.variable} ${manrope.variable} ${pacifico.variable} `}
      >
        <HeaderClient />
        {children}
        <FooterServer />
      </body>
    </html>
  );
}
