import localFont from "next/font/local";
import "./globals.css";
import HeaderClient from "@/components/global/HeaderClient";
import FooterServer from "@/components/global/FooterServer";

const inter = localFont({
  src: "./fonts/Inter_18pt-Medium.ttf",
  variable: "--font-inter",
});

const nunitoSans = localFont({
  src: "./fonts/NunitoSans_7pt_Condensed-Regular.ttf",
  variable: "--font-nunito-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${nunitoSans.variable} `}>
        <HeaderClient />
        {children}
        <FooterServer />
      </body>
    </html>
  );
}
